### ISSUE TITLE
Update repo documentation link

### ISSUE THREAD

**Issue by mpadge** [ropensci/aorsf#10]
@bcjaeger Congatulations on getting the first "gold standard" package through rOpenSci's peer review process! Could you please update the webiste link in the repo settings here to https://docs.ropensci.org/aorsf? Thanks! Mark

**Comment by bcjaeger** [comment]
> Congatulations on getting the first "gold standard" package through rOpenSci's peer review process!

That is awesome. Thank you!! 

The link has been updated. I will see about getting a more blue hex sticker to match this new environment for `aorsf` =]

**Comment by mpadge** [comment]
No way :scream: the hex sticker is brilliant as is! [vaporwave](https://github.com/moldach/vapoRwave) all the way!
