### ISSUE TITLE
Are classification and regression supported?

### ISSUE THREAD

**Issue by ggrothendieck** [ropensci/aorsf#14]
obliqueRF is no longer on CRAN since May.  Can aorsf be used for classification and regression or is it only for survival trees?  Are there any examples?

**Comment by bcjaeger** [comment]
`aorsf` supports survival forests and doesn't do classification or regression yet. I have both of these in mind for a future update, but I need to get funding for it. If you know of any grants that would be open to this kind of project I'd be all ears!
