### ISSUE TITLE
survival learner issues in via mlr3

### ISSUE THREAD

**Issue by bblodfon** [ropensci/aorsf#49]
Hi Byron,

Just tried to use `aorsf` with survival data via `mlr3extralearners` and got this error:
``` r
library(mlr3extralearners)
library(mlr3pipelines)
library(mlr3proba)
#> Loading required package: mlr3

task = tsk('lung')
pre = po('encode', method = 'treatment') %>>%
  po('imputelearner', lrn('regr.rpart'))
task = pre$train(task)[[1]]
task
#> <TaskSurv:lung> (228 x 10): Lung Cancer
#> * Target: time, status
#> * Properties: -
#> * Features (8):
#>   - int (7): age, inst, meal.cal, pat.karno, ph.ecog, ph.karno, wt.loss
#>   - dbl (1): sex

aorsf = lrn('surv.aorsf', control_type = 'fast',
  oobag_pred_type = 'surv', importance = 'anova',
  attach_data = TRUE)

aorsf$train(task)
#> Error: some variables have unsupported type:
#>  <status> has type <logical>
#> supported types are numeric, integer, units, factor, and Surv
aorsf$errors
#> character(0)
```

<sup>Created on 2024-04-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Maybe you haven't updated it with recent changes? I see for example that the `oobag_pred_type` default is `risk` now, not [`surv`](https://github.com/mlr-org/mlr3extralearners/blob/main/R/learner_aorsf_surv_aorsf.R#L61).

**Comment by bblodfon** [comment]
Btw is the `mort` prediction type the same as in RSFs? Eg adding the cumulative hazard for all time points for each observation? Something like:
```
cumH = -log(surv_matrix) # surv_mat is (obs x times)
cumH[cumH == Inf] <- 0
rowSums(cumH)
```

**Comment by bblodfon** [comment]
1. Yes please! It make sense with `status`, only a few datasets have `TRUE`/`FALSE` instead of an `integer` 0 or 1 and if you want to go multi event in the future, checking/converting to integer is the way to go.
2. Haha yes, let's just make sure everything is updated when you have the time in `mlr3extralearners`, I can double-check the PR if you want. Including the `response = rmst` prediction could be also included as an extra that would be nice.
3. Super

I will be heavily using `aorsf` soon and I was glad to find other things to be solved. There was some C++ issue when running with extremely large datasets (~30K features) if I find it again, I will let you know!

**Comment by bcjaeger** [comment]
> I will be heavily using aorsf soon

This absolutely made my day. Thank you!! 

I will get to work on the patch and the addition of `rmst` in `mlr3extralearners` soon (sorry I have been slow on the `rmst` PR - it is on my short list of priorities now).

**Comment by bblodfon** [comment]
Hi @bcjaeger! Would you have time to quickly look and update the PR in `mlr3extralearners`?

**Comment by bblodfon** [comment]
I updated the `tsk("lung")` of `mlr3proba` to encode `status` as 0/1 so the original issue is no longer present.
