### ISSUE TITLE
Error in matrix(data = c(collapse::fnth(numeric_data, 0.1, w = self$weights),  :    'data' must be of a vector type, was 'NULL'

### ISSUE THREAD

**Issue by cmululu** [ropensci/aorsf#55]
For the oblique random survival forest model, if there is only one independent variable in the data except for the time and event. The error will happen.

![image](https://github.com/ropensci/aorsf/assets/7980962/cc1ccfd0-4d9d-4828-a969-da4040c5ce52)
![image](https://github.com/ropensci/aorsf/assets/7980962/3943ad40-0fae-43f1-b1d3-643da46edf0a)

**Comment by bcjaeger** [comment]
Thanks! Would you be comfortable providing a reprex for this error? I will check it out a little more carefully and see if it's feasible to work in a fix. 

For oblique random forests, you don't gain anything from including fewer than 2 predictor variables. Oblique splitting with 1 variable is the same thing as axis based splitting.

**Comment by bcjaeger** [comment]
PR #56 should fix the error you received. Please don't hesitate to let me know if there are still issues after you download the development version of `aorsf`
