### ISSUE TITLE
Question about na_action = "impute_meanmode"

### ISSUE THREAD

**Issue by alkat19** [ropensci/aorsf#66]
In the case where we have missing data on the testing set, is the imputation done based on the mean&mode of the testing set or the training set?

**Comment by bcjaeger** [comment]
Hello! 👋 

Good question. The mean and mode values used to impute missing data are computed in the training set when the `aorsf` object is fitted and then used to impute new values in testing data.

**Comment by alkat19** [comment]
Excellent, so there is no data leakage. Thank you for the fast reply.
