### ISSUE TITLE
Question: Support for time dependent/varying covariate modeling in the survival regression context

### ISSUE THREAD

**Issue by instantkaffee** [ropensci/aorsf#69]
Does aosrf support time dependent/varying covariate modeling in the survival regression context?
See concept here: https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf

Just to 100% sure I do not mean time varying effects.

Please let me know.
Thanks

**Comment by bcjaeger** [comment]
Thanks! Sorry, no current support for time-varying covariates.
